import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { Header } from '@/components/header'
import './globals.css'

const integralCF = localFont({
  src: [
    {
      path: '../../public/fonts/Fontspring-DEMO-integralcf-bold.otf',
      weight: 'bold',
    },
    {
      path: '../../public/fonts/Fontspring-DEMO-integralcf-extrabold.otf',
      weight: '800',
    },
    {
      path: '../../public/fonts/integralcf-heavy.otf',
      weight: '900',
    },
  ],
  variable: '--font-integralcf',
})

const satoshi = localFont({
  src: [
    {
      path: '../../public/fonts/Satoshi-Bold.otf',
      weight: '700',
    },
    {
      path: '../../public/fonts/Satoshi-Regular.otf',
      weight: 'normal',
    },
    {
      path: '../../public/fonts/Satoshi-Medium.otf',
      weight: 'normal',
    },
    {
      path: '../../public/fonts/Satoshi-Light.otf',
      weight: '100',
    },
    {
      path: '../../public/fonts/Satoshi-Black.otf',
      weight: '900',
    },
  ],
  variable: '--font-satoshi',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${integralCF.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
